version: 0.2

phases:
  install:
    commands:
      - echo Installing everything...
      - npm i npm@latest -g
      - npm install
    finally:
      - echo Dependencies installed successfully.
  pre_build:
    commands:
      - echo Running tests...
      - npm run test
    finally:
      - echo Tests passed successfully.
  build:
    commands:
      - echo Building Gatsby...
      - npm run build
    finally:
      - echo Nice Going Gatsby! Build finished successfully.
  post_build:
    commands:
      - aws s3 sync public/ s3://chrispachom.ski
      - aws cloudfront create-invalidation --distribution-id "${CLOUDFRONT_DISTRIBUTION_ID}" --paths /*
    finally:
      - echo Artifact pushed to s3 successfully.
