version: 0.2

phases:
  install:
    commands:
      - echo Installing everything...
      - sudo apt-get update
      - sudo apt-get --assume-yes install chromium-browser
      - npm i npm@latest -g
      - npm install
    finally:
      - echo Dependencies installed successfully.
  pre_build:
    commands:
      - echo Building Gatsby...
      - npm run build
      - echo Building Storybook...
      - npm run storybook:build
      - echo Running Tests...
      - npm run test
    finally:
      - echo Nice Going Gatsby! Build and Tests finished successfully.
  post_build:
    commands:
      - aws s3 sync public/ s3://chrispachom.ski
      - aws cloudfront create-invalidation --distribution-id "${CLOUDFRONT_DISTRIBUTION_ID}" --paths /*
    finally:
      - echo Artifact pushed to s3 successfully.
